default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: henokkh
  password: 123456
  pool: 5

development:
  <<: *default
  database: rails_blog_app

test:
  <<: *default
  database: rails_blog_app

production:
  <<: *default
  database: rails_blog_app
